language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'using Pkg; Pkg.add(PackageSpec("BinaryProvider", rev="master"))'
- julia -e 'using Pkg; Pkg.add(PackageSpec("BinaryBuilder", rev="master"))'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: Bv4/ouslpqekDcbBD8E6M9a4aVOeOz+FRh9zL3cpvtRr8CcJu3eJjhv4QU2AI4MvjqQYYZyE4tvKVKU4D7GP/d6MzyPeJSGI6jeptLBhYmlor1zSsnLANc+ZTvrQyzAvEsdJ99jtcHdobk/6lKHemB8Bi1MeM5yLff6iPqkmM3sPIHgOAE9vb1OAaum9s+rvzDK1gUIXiK9DFotBO0NF6LvHA3TDTww5AHjDCWUBo8Ou6ySP/ZWCudYtGiKR6JQisLZQwxNayGFjUey197CZQ+PuCKR3x1oIGH7av6mePPk0gEy85sWHZhSnVReJHojKhL1Go+jiSF/j+aLnucmOfDRCXaq0xOoRMLwfoSE/ZpcBhvjedqN4aTyWhy2Xy4VALEZbEtcHrqMUJHma949LQtVW+XKrUfrQyMwUL3obInhguwIy2y0tVFA0XwolC9HOuzl/TYOvjOC5yf2hNvBaWLaE0vzLbe6sQAkRYhV/Mruqci1YEi3i2A8FZrqrj5qTpzjtKAfsYYbZSUXDIbtCnf4zFhY58dl+TGryLMRoDMnv7Qa6HTx1hvWDE5MXDnLiwLu9EteksddkNxqQFZMSV1h/ydsD7g8Gkg+5lrQ6eTRNPyxdIaVmDpyr5SN/1auNrg1upLy2ew37cDePId6NvQClHINgQYvN3SWFKQzg81M=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: jstrube/Minuit2Builder
    tags: true
